# Generated by Django 4.0.2 on 2022-02-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_is_delete_userfavorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorite',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='userfavorite',
            old_name='user_id',
            new_name='user',
        ),
    ]
