# Generated by Django 4.0.2 on 2022-02-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_genres_alter_movie_imdb_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
    ]
