# Generated by Django 4.0.2 on 2022-02-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='img/no-image.jpg', null=True, upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(blank=True, default='title is unavailable', null=True),
        ),
    ]
